version: '3.7'
services:
    web:
        build: .
        env_file:
          - .env
        ports:
          - "3000:3000"
       
        command: air ./cmd/main.go -b 0.0.0.0
    db:
        image: postgres:12
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        ports: 
          - 5432:5432
        logging:
          options:
            max-size: 10m
            max-file: "3"
    pgadmin:
        image: dpage/pgadmin4
        environment: 
          - PGADMIN_DEFAULT_EMAIL=admin@email.com
          - PGADMIN_DEFAULT_PASSWORD=admin
        ports: 
          - "5050:80"
